spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Gowtham - QA Manager"
    email: "gowtham@eazybank.com"
  onCallSupport:
    - (888) 555-0001
    - (888) 555-0002
